name: cvae_steppingstone
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - matplotlib
  - sympy          # 쓰면
  - pytorch        # or pytorch-cpu, 환경에 맞게
  - torchvision
